Q1="SELECT COUNT(id) FROM Movie WHERE year<2000;"
Q2="SELECT AVG(rank) FROM Movie WHERE year==1991;"
Q3="SELECT MIN(rank) FROM Movie WHERE year==1991;"
Q4="SELECT fname,lname FROM Actor INNER JOIN cast on id==pid where mid==27;"
Q5="SELECT COUNT(mid) FROM Actor INNER JOIN Cast on id==pid where fname='Jon' and lname='Dough';"
Q6="SELECT name FROM movie WHERE name LIKE 'Young Latin Girls%' and (year BETWEEN 2003 AND 2006);"
Q7="SELECT DISTINCT fname,lname FROM (Director d INNER JOIN MovieDirector md on d.id=md.did) INNER JOIN Movie m on m.id=md.mid WHERE m.name LIKE 'Star Trek%' GROUP BY d.id HAVING COUNT(m.id)>=1;"
Q8="SELECT name FROM Movie m INNER JOIN MovieDirector md  INNER JOIN Actor a  INNER JOIN Director d  INNER JOIN cast c  on m.id=md.mid and c.mid=m.id and d.id=md.did and a.id=c.pid where (a.fname='Jackie (I)' and a.lname ='Chan') and  (d.fname='Jackie (I)' and d.lname ='Chan')  Order by m.name asc;"
Q9="SELECT fname,lname FROM (Director d INNER JOIN MovieDirector md on d.id=md.did) INNER JOIN Movie m on m.id=md.mid WHERE m.year=2001 GROUP BY d.id HAVING COUNT(m.id)>=4 Order by fname ASC,lname DESC;"
Q10="SELECT gender,COUNT(id) as count FROM Actor a group by gender order by gender ASC;"
Q11="SELECT DISTINCT a.name,b.name,a.rank,a.year FROM MOVIE a CROSS JOIN Movie b on a.name!=b.name and a.rank=b.rank and a.year=b.year order by a.name LIMIT 100;"
Q12="SELECT a.fname,m.year,avg(m.rank) from ACTOR a INNER JOIN cast c on a.id=c.pid INNER JOIN Movie m on c.mid=m.id group by a.id,year ORDER BY a.fname ASC,m.year DESC LIMIT 100;"

#Q12="SELECT a.fname,m.year,m.rank from ACTOR a INNER JOIN cast c on a.id=c.pid INNER JOIN Movie m on c.mid=m.id ORDER BY a.fname ASC,m.year DESC LIMIT 100;"
#Q13="SELECT a.fname,d.fname,avg(m.rank) as score from Actor a INNER JOIN cast c on a.id=c.pid INNER JOIN Movie m on m.id=c.mid INNER JOIN MovieDirector md on m.id=md.mid INNER JOIN Director d on d.id=md.did group by md.did,a.id  having COUNT(m.id)>=5 ORDER BY score DESC,d.fname ASC,a.fname DESC LIMIT 100;"
Q13="SELECT a.fname,d.fname,AVG(rank) as score from actor a inner join cast c inner join movie m inner join moviedirector md inner join director d on a.id=c.pid and m.id=c.mid and m.id=md.mid and d.id=md.did group by a.id,md.did  having COUNT(m.id)>=5 ORDER BY score DESC,d.fname ASC,a.fname DESC LIMIT 100;"